server:
  port: ${PORT}

spring:
  flyway:
    locations: classpath:/db/migration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mailgun:
    username: ${MAILGUN_USERNAME}
      password: ${MAILGUN_PASSWORD}