server:
  port: ${PORT}

spring:
  flyway:
    locations: classpath:/db/migration
  database: ${DATABASE}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

